name: mille-bornes # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: DOS version of the game Mille Bornes
description: |
  DOS version of the game Mille Bornes

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mille-bornes_icon.png
title: Mille Bornes (DOS)

apps:
  mille-bornes:
    command: dosbox MILLEBRN.EXE
parts:
  mille-bornes:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [dosbox]
    stage-packages: [dosbox]
    organize:
      mille-bornes: build/
      mille-bornes.1: man/man1/

architectures:
  - build-on: amd64

